character_descriptions = [
    "Kory:",
    "- The friend they all look up to",
    "- Believes he is handsome and super tall",
    "- Thinks he's the best at everything he does",
    "- Considers himself to have the best \"rizz\" (charisma/charm)",
    "- His self-perception may not align with reality",
    "- Leader of the group",
    "- Funny and a jokester",
    "- High energy",
    "- Best friends with Kai",
    "- Secretly has a crush on Brooke but won't admit it",
    "- Weirded out by Brooke's affection towards him",
    "- Thinks Star is a nerd but cute",
    "Brooke:",
    "- Described as a \"firehead\" (likely redhead)",
    "- Quick-tempered, set to go off at any moment",
    "- Madly in love with Kory",
    "- Best friends with Star",
    "- Often deals with Kai",
    "- Physically the strongest in the group, even stronger than Kory",
    "- Mean and a bully, especially to Kai",
    "- Obsessed with Kory",
    "- Described as \"lowkey psycho\"",
    "- Stalks Kory",
    "- Violent and uses force",
    "- Girl besties with Star",
    "Star:",
    "- The book-smart nerd of the group",
    "- Very sweet, kind, and wholesome",
    "- Comes from a very rich background",
    "- Almost a genius in intelligence",
    "- Sometimes misses obvious things",
    "- Creates inventions that enable crazy adventures",
    "- Without her creations, the group would miss out on some adventures",
    "- Worried about a lot of stuff",
    "- Best friends with Kai",
    "- Friendzones Kai but oblivious that he likes her",
    "- Classic adorable girl character",
    "- Girl besties with Brooke",
    "Kai:",
    "- Described as a \"lost puppy dog\" and \"empty-headed monkey\"",
    "- Dumb and clueless",
    "- Very \"sus\" (suspicious)",
    "- Funny and a jokester",
    "- Likes pranks",
    "- Classic comedic dumb character",
    "- Likes cookies and video games",
    "- Has a crush on Star",
    "- Nervous around girls",
    "- A massive troll",
    "- Makes the rest of the group feel smart like Star",
    "- Short in stature",
    "- Loved by the group despite his quirks",
    "- Best friends with Kory",
    "Group dynamic:",
    "- Referred to as the \"fantastic four friends\"",
    "- They're like a family",
    "- Every day is a wild, fun journey for them",
    "- They have whacky times together",
    "- Happy to share their experiences with their audience"
]