selected_sentence_samples = [
    "Oh my goodness, I can't believe I got lost again!",
    "I was literally just out for a little bit of a walk, and I guess I did real time far I've been walking because now I am stuck in the forest.",
    "It is so dark outside and there are so many legion trees here that I don't know how to get out.",
    "Oh my gosh, now there's even thunder!",
    "Well, I guess I'm just gonna have to find someone that lives around here and ask them for help.",
    "Oh, that's super duper sad, but let's check out this house.",
    "There's even like cobwebs here and stuff, it must be super duper old.",
    "Oh no, did I just step on this trip wire? Did that activate something?",
    "Am I gonna get stuck in a trap too?",
    "I can't take this anymore, I'm sorry, I'm on my way.",
    "Hello, hello mister... mister villager, why are your eyes like that?",
    "Oh no, this is giving me a super duper ultra bad feeling.",
    "Oh wait, this is a village! Oh maybe there's actually some villagers left, like this guy, but he's just super weird so he's not talking.",
    "He's stuck in another trap. Are you okay? Are you okay?",
    "And he's not responding. I think he may not be alive anymore.",
    "What is wrong with this place? No no no, this is super bad, this is super bad.",
    "Oh my goodness, why are there a bunch of dead humans stuck in here?",
    "No no no, is this village haunted or something? Or is there a murderer nearby?",
    "This is super duper ultra bad! Oh my gosh, I need to get out of here, I need to get out of here!",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Is he watching me? Hello, hello, can you watch me? Are you seeing me?",
    "Like, what is around all of this? It just looks like a place where he does experiments or something.",
    "Hello buddy, buddy are you okay? You gotta speak to me man, you gotta speak to me!",
    "Oh, 'run', that's all you can tell me?",
    "And oh my goodness, this guy is huge! How did they ever capture him?",
    "And oh my goodness, look at his eyes and his teeth! Why does he look so scary?",
    "Why is everybody telling me to run? Well, probably because the evil villager is gonna like, kill me somehow.",
    "But still, this is so scary and he has even more people here. Look how terrified they look!",
    "And I'm so sorry guys, but I don't think I can escape with you. You guys are way too noisy and there's just too many people.",
    "So I have to do this by myself and there's a thing called a security... what's inside the security room?",
    "Literally nothing just happened, the camera just disappeared.",
    "But let's keep exploring and... oh, oh this is the torture chamber. Okay, I see, I see.",
    "So we need to figure out how to open the valve over here first and is there anything else this way?",
    "And whoa, there's a set of stairs here. Alright, let me go down over here.",
    "Is there anything here? Nope, I don't see anything.",
    "Here's the living... what is that? Is that... is that the evil villager?",
    "No no way, no way, no way! Wait, wait, there's a chest here and there's a bunch of stuff in here including a shield.",
    "Okay, let me equip that real quickly and... oh no no no no!",
    "Oh my god, he's right there, he's right there, he's right there!",
    "Wait, wait, did I do this wrong? Oh my goodness, it's one seed in four dirt!",
    "I thought it was the other way around! Oh, so we got all those seeds for nothing.",
    "I knew I shouldn't have beat up that pig.",
    "Oh my, it is... this is actually insane! I'm flying!",
    "I'm like kinda glitch flying though, but you know what? I'm still flying!",
    "What is this, the poop of Thanos? Do I have Thanos poop in my hands?",
    "Oh, such a good idea! Let me just float straight up into this sky, like super high.",
    "Oh my goodness, I've been searching for this for so long! Hello, Missus Sugarcane, it's so very nice to meet you!",
    "Yo, I am fitted out! This means I don't only get superpowers, I also get super OP items!",
    "I just realized I'm like farting to fly. This is so funny!",
    "I'm finding way more diamonds than I am coal right now. Wait, I see coal! I see coal!",
    "Did I just get a golden apple? Oh my goodness, wait a minute, this is actually so OP!",
    "Wait, why do I have two souls of babies? Okay, okay, guys, yeah, give me a second. I'm trying to do something here.",
    "Gosh, it's so rude just interrupting me while I'm trying to record!",
    "Hey, everyone who was chasing me before, where you at? Oh yeah, look at that! Look at that guy, just disappeared!",
    "And holy moly guacamole! What is this?",
    "This can literally kill the Ender Dragon in one hit!",
    "Yeah! Oh, it just insta-kills everything! No matter what, I can literally spam click and just kill them!",
    "Oh my goodness, I can't fly in the Nether! This means I have to walk like a peasant!",
    "So we got all the nuggets. Chicken nuggets!",
    "Wait, why have I been scared? I have my abilities!",
    "Come here, Mister Blazes! Give me your blaze rods!",
    "Fly away! Oh gosh, nope, nope, nope, nope! Not at all, not at all, not at all, not at all!",
    "It's literally just helping me get lazier and lazier! So I can fly and I can teleport!",
    "How do you make a clock? Wait a minute, now I'm thinking about it, I literally don't know how to make a clock.",
    "Please be redstone, drop me redstone! Drop me redstone, please!",
    "They're probably so confused right now! Oh, look at this one! He's mad! He's mad that I took away his brothers!",
    "Don't worry, you'll be joining them! Oh gosh! Oh, that was hilarious!",
    "You know what? Never mind, the water ruined it for me. I just locked this up and...",
    "Please, portal room, where are you? Imagine the portal room actually responds! I... I'm right here!",
    "Wait, why? It's right here! Oh my goodness, what the heck? That's actually so unexpected!",
    "Come here, Ender Dragon! I'm coming for your body!",
    "And wait, this infinity bow is like... kinda sucks actually. It doesn't do that much damage.",
    "Oh, wait, I can't kill him! I gotta send him to the dark dimension! Come here, Mister End...",
    "Oh, wait, does it not work? Wait, where am I? What am I stuck in the obsidian?",
    "Oh my goodness, I literally teleported into the obsidian accidentally!",
    "I think we learned today that I should not be trusted with power.",
    "But that's it for today, and I will see you guys later!"
    "Oh my goodness, look at my heart right now! I literally have a heart right if I someone at Thor and I'm gonna die right now.",
    "Wait, what are these textures? Where even am I? This doesn't even look like Minecraft, this just like mine poop.",
    "This is worse than the normal Minecraft graphics, which you know aren't that great themselves.",
    "I can't even tell what this is. What... what even is this? It's a... it's a cornflour?",
    "Why does the stick just like square? Oh god, how is this a wooden pickaxe? This literally makes no sense!",
    "I kinda wonder what the dragon in this realism would look like. Like, would it just be a giant potato floating around?",
    "Wait, what the... what is that? Is this a cow? The cow literally has no face whatsoever!",
    "Are you sure about that? Alright, I'm sorry Mister Cow, but you guys are gonna have to go.",
    "I think we just encountered our first mob. Is that a... that a zombie? And oh gosh, it's on fire!",
    "Oh gosh, you just gotta sink everything's like eight... Wait, wait a minute, what? I... I can't look out of my body?",
    "Hello sir and oh... okay, he looks kinda normal. Okay, why are you staring at me so intently bro? Chill out!",
    "Whoa, he looks like a robot with this texture pack on! He looks awesome!",
    "Number one rule of Minecraft: never let villagers be happy. Isn't that Mister Villager? Uh-oh... okay, okay, well that was a little scary.",
    "Oh my goodness, I can literally see myself carrying this shield too! This is so wonky!",
    "Did he just smile at me? I swear he just smiled!",
    "Okay, come on Mister Piggy! Oh wait, he snows! It's like... it's okay! Do you see that?",
    "Oh my goodness, that is adorable! Look at punching him and he has a different head of it!",
    "You know what? Maybe we should stop harassing the animals.",
    "We gotta be super duper careful because last time we died right away because I didn't notice the skeleton behind me.",
    "Oh gosh, there are a lot... there are a lot of zombies here! Oh gosh, I'm a lot... oh, I need a fire! I'm a fire! I can't even see!",
    "I'm really scared that like out of the blue a zombie just gonna appear and it just look my brain.",
    "Give me the... yeah, give me the idea! I... I don't know why I'm talking in that voice. I'm sorry.",
    "Honestly, twenty iron should be fine enough. I did not want to spend another second down there.",
    "Whoa... okay, this is Minecraft if it was like ultra cool!",
    "Look how awesome everything... Oh my goodness, look at the iron ore! That literally lights up!",
    "Wait a minute, is that a circle? Is the sun a circle in Minecraft? No no no, this thing's no sense! A circle should not be in my... white circle?",
    "I'm actually scared. I barely have four hearts, what am I gonna do?",
    "I've already said this is insane like twenty-three different times, but this looks insane!",
    "Okay, come here, come here, come here! There are more spawning, there are more spawning! There are three in my face right now!",
    "Editor, please do a cool montage of me killing the Enderman!",
    "What the heck? Oh my... why is this... what is this? No, this actually looks disgusting!",
    "What am I looking at here? This is not like more realistic. I... I mean I guess it does like more realistic, but like it looks terrible!",
    "Oh my goodness, that is the cleanest water I've ever seen in my entire life!",
    "This is the first time I've broken a tree and it's crumpled down, not stayed standing up!",
    "Oh gosh, this is scary! Oh, I need to eat! Did eat! There are so many mobs here right now!",
    "Whoa, look at the obsidian too! That is literally insane! This is so sick!",
    "Oh my goodness, mine is the craziest clutch! Anybody see that? Wait, I mean, of course you guys saw, you're watching the video, but still!",
    "Oh no no no no... okay, he's back! He is backed out! Come on!",
    "Wait, I did it! I did it! Let's go!",
    "Anyway, that's it! Peace guys, have a great day",
    "This is Minecraft but me and my friends are trapped on this one block world and if that wasn't hard enough our world is getting more realistic every minute.",
    "I think we're on one block but why does the block look so different?",
    "I'm not sure but this thing says to break the block below you. Should we do it guys?",
    "Oh sorry, I didn't mean to do that.",
    "Sorry sorry sorry, but wow this is weird. Well, let's just keep breaking the block and see what happens. Maybe our game will upgrade in realism as we continue to expand.",
    "Yeah, wait, this is a little bit creepy. Oh my goodness, it doesn't have a butt guys!",
    "How is it cute? It literally has nothing on his face!",
    "Yeah, you're right. Here, let's just move it over to the side and oh, another chest! Hey, stop taking everything! What'd you get?",
    "Wait, wait guys, let's play guess item! What item am I holding right now?",
    "Yeah, everything is just blocky and squares. I'm not sure I like this very much guys.",
    "What do you think this one is?",
    "I mean maybe. It looks super duper weird though.",
    "Yeah, yeah, whatever Star. Let... let me just pick this back up so nobody falls off.",
    "Alright, well let's just keep breaking the block. Hopefully our realism will upgrade soon and wait, guys, do you feel that?",
    "I think it might be your butt, but I feel it too. No, not in my butt and oh my goodness guys!",
    "No, I think you are the weird one here.",
    "And wait, speaking of weird, look at his pig! His eyes are... they're literally just pure darkness!",
    "Little beady eyes? Why are you saying that's just cute? Ace, look at it! This thing is pure evil, man!",
    "Yeah, it's pretty scary and I'm getting a little bit hungry. Oh my goodness guys, look at what happens when I eat! I can't see my own arm in my face!",
    "Yes, let's go! Oh my goodness! Alright, here we... let me just build around this entire thing here real quick, make it a big island.",
    "Boom boom boom! Alright, you keep digging. I'm gonna make myself some tools so we could dig even more.",
    "Wait, you're right!",
    "Okay, okay, here I'm just gonna place the water bucket inside the chest and you guys can do what you want with it, but I'm gonna make a shovel real quick.",
    "No, what does it look like?",
    "Wait, let me try! Let me try! Oh, wait, you are right! This is weird! Hey, wait, what the heck? What the heck? Hey, check it out! We got two pigs!",
    "No thing... that I meant... I meant Ace! Ace is a pig! I wasn't referring to you Star, I meant Ace!",
    "And what do you mean good save? That's what I was talking about all along, Star!",
    "Wait, why are we getting the entire animal farm on our base? We gotta build these guys like some fences or something, yeah?",
    "Yeah, let me make a bunch of wood real quick. Okay, I got a bunch of fences. There we go, let me just put these guys all in the corner and make sure they don't fall off. Come on, come on piggies, get over there!",
    "That is true. Or we could always, you know, eat some food. You know what I mean?",
    "Oh my goodness, are you serious? Okay, you don't wanna... Sheep, you're dying! Oh!",
    "Yeah, be too! And wait, Ace, this is a nice farm, but we don't have any seeds.",
    "Oh, okay, okay, okay. Here, I have some lemon seeds too. Give me the pumpkin seeds so we can plant all of them for unlimited food!",
    "Okay, just... just plant them and wait, I can't even tell if we're planting them. This is so weird!",
    "Oh wait, I see!",
    "Wait, really? I thought you had to like, make it a line.",
    "Oh, okay, that's cool!",
    "What? Why am I not surprised at all?",
    "Wait, there's so many! How many chicken... out of this too?",
    "Alright, boys in the farm! Get in the farm guys! Somebody... they're escaping!",
    "Well, what other one?",
    "Oh guys, no, I think it's happening! Oh gosh, oh no no... Oh my goodness, we... we upgraded again! Look at this! Shadows! This is awesome! It looks so cartoony!",
    "I know, and whoa, look at the crops!",
    "And they're swaying in the wind! Hey, check this out!",
    "Yeah, and wait, even the water is animated too!",
    "Oh, well maybe that'll happen in the next realism, but this is pretty sick. I mean look at the... and what the... yo!",
    "Oh my goodness, wait, do these guys have different animations?",
    "Here, let's try punching this guy, see how he...",
    "He's like using all four legs to run! That's so cool!",
    "Oh, well, it... it just looks like he dies. That's by fault, Ace. Oops!",
    "Well, we need it for food, okay? That's what I'm getting, right?",
    "Okay, fine, there... there's still enough left here. Does anybody have any carrots? I wanna bring these guys over.",
    "Well, I'm a just scooch you guys over. Get over there, Mister Piggy!",
    "Yeah, here... Oh my goodness, no, he's coming back! You think it's funny, Star? You think it's funny?",
    "Mister Pee Pee Poo Poo is gonna get it if you think it's funny!",
    "Yeah, yeah, right! And stop blinking, Mister Pee Pee Poo Poo! It's not natural!",
    "Yeah, I'm trying to push these guys! These pigs and these cows are literally just ruining my life right now! Okay, there we go!",
    "Yeah, Star! And wait, Ace, can you give me some blocks? I ran out!",
    "Just give me everything!",
    "That's all the dirt you... Okay, give me some other blocks, man!",
    "Wow, okay, I guess this will be good enough. And you know what? I think we should name this house the Corey House!",
    "Because I'm the leader of this group, guys, obviously!",
    "Yeah, I mean the farm's cool and all, but I mean we gotta give it to the most handsomeness, and you know that's obviously me!",
    "What do you mean 'in your dreams'? I... Hey Star, what are you doing? These guys are escaping!",
    "Oh my goodness, that's... I'm... I'm pushing them in right now! I gotta solve all the work, don't I?",
    "Okay, what... what do you... Oh, you're expanding the farm! Exactly! Oh, that's actually pretty good! But they're still escaping! They're trying to get in the house!",
    "It's not okay! This house is not for humans! It's not for animals! And you know what? I guess it's... Star, here it is okay!",
    "And you can't deny that it's facts!",
    "Yeah, just because I told the truth, Story, doesn't mean you have to get mad at me!",
    "It was a joke and... oh gosh, guys, I feel it again! The funny feeling! Already! Oh gosh, here we go!",
    "And whoa, this looks completely different!",
    "Why do the animals look like this?",
    "Dude, Star, I just saw one blink!",
    "Wait, what? Let's see... Oh! Does it? This is pretty cool actually! And oh my goodness guys, check it out! Look at the hoodies! It's a circle! That's not... that's really isn't... what the... yo!",
    "Circles shouldn't be in Minecraft, Star!",
    "I mean, I guess so, but I'm just saying it's a... it's a little bit weird. But our house does look a lot better now that it's more realistic!",
    "And guys, what is happening with this farm? Everybody is in the house, not even in the fences!",
    "Well, you know what? I'm a fix that! I'm gonna fix it, guys!",
    "Oh my goodness! Well, we need it for food, okay? That's what I'm getting, right?",
    "Okay, fine, there... there's still enough left here. Does anybody have any carrots? I wanna bring these guys over.",
    "Well, I'm a just scooch you guys over. Get over there, Mister Piggy!",
    "Yeah, here... Oh my goodness, no, he's coming back! You think it's funny, Star? You think it's funny?",
    "Yeah, yeah, right! And stop blinking, Mister Pee Pee Poo Poo! It's not natural!",
    "Yeah, I'm trying to push these guys! These pigs and these cows are literally just ruining my life right now! Okay, there we go!",
    "Apples! That's not bad, that's not bad! And whoa, wait, these fences look awesome!",
    "Is... is this upgrading? Another upgrade? I don't know, let's see, let's see, let's see! And wait, what? Underground many a monster roam through dark hollows! There's monsters?",
    "Oh gosh, guys! Monsters are gonna come!",
    "Wait, but at least we have cobble so now...",
    "Yeah, I have no doubt you will! Oh my goodness, wait! Hey Star, remember you said about the water?",
    "Yeah, we can! And wait, I kinda wanna like spread this water out, so I'm gonna go below and like build a little basin underneath it.",
    "Wait, no no no! I'm gonna die! That's the problem, not the water!",
    "I'm good, I'm good!",
    "Okay! Oh my goodness! Alright, I'm not attempting that again!",
    "You know what, Star? I don't wanna hear it, okay? You're not even helping out! Ace and I are doing all the work right now! Can you grab a pickaxe and get to it? No... no, with your fist? Seriously? How do you think that's gonna help? And what is that?",
    "Wait, I don't even know what this is. It's definitely isn't...",
    "Wait, what is this? Hold on, hold on! Don't break it, don't break it! Let me craft a better pickaxe and try! Alright, I got a stone pickaxe. Okay, let's see what this baby is and... What? It's still breaking slowly!",
    "Oh, wait, I'll use my wooden pickaxe! Okay, hold up... It is... Oh, it's iron! Okay, perfect! Here, we can use that to our advantage!",
    "What the... yo! Why does it look like that?",
    "There's... look at the mushrooms on this side! It's so realistic!",
    "Oh, wait, you're right! Hold on, let me grab this real quick! Oh, okay, everybody grab a mushroom stew! We're gonna eat this together! That's so delicious!",
    "Yeah, we know... Wait a minute, guys, I don't know if it's just the mushroom stew, but I don't feel so good!",
    "Oh gosh, guys! Oh no, I think we're upgrading again!",
    "And animals, they... gosh, they're back to normal! That was a little bit creepy!",
    "Wait, guys, look at this water! Wait!",
    "It's so much more realistic! Whoa, it's so clear! I know, and oh my goodness, did you see the grass too? And it's like little like saplings are growing within them!",
    "Do you see how realistic that is? This is insane! Hold up, I'm gonna build a little bit of a hot tub and I wanna see what the water looks like!",
    "Okay, here... Who has the bucket?",
    "Okay, okay, let's see... Oh, even the bucket looks cool! Oh my goodness, that is insane! Whoa!",
    "It is like rippling! That is awesome!",
    "This is insane! Oh, my goodness, guys!",
    "Wait, I wonder if it tastes good. I feel like I could drink it!",
    "Oh, that's nasty! Oh, what is wrong with this water?",
    "Wait a minute, why does it look a little bit yellow?",
    "Oh my goodness! It is... What? That is disgusting! Oh god! Wait, I don't see if a sword looks different though. Let... let me see and... Oh, never mind, it just looks the same.",
    "Okay guys, right now we are driving up to my friend's house and I've been hearing rumors about the secret USB drive that he has and I need to get it so I can find what his secrets are. I'm actually really curious what it could be.",
    "Alright guys, now is the perfect time to look for his core USB drive. Okay, where could it be? I literally don't see anywhere within his room.",
    "Maybe it's on his desk somewhere... A Grayish Shake? Happy birthday bro! Really? He got the Grayish Shake? I was broke... still alive... Wait, wait, what is this? Oh my gosh, we got it guys! We got it! We got it!",
    "Okay, okay, okay! Holy... I can't believe we actually just found it!",
    "Nothing! I gotta go! Bit... I gotta go! What? Sorry, to... No way! We actually got it! We got the USB!",
    "Whoa, where did I just spawn? It looks like I just spawn in some sort of like mansion place.",
    "What the heck was that? What is that noise? What... what the... yo! Oh my goodness, that actually made my heart stop for a second!",
    "I do not have a good feeling about this at all. Oh gosh, I'm really nervous.",
    "Thunder, can you chill out? I'm trying to record a video, please!",
    "Whoa, it looks like a meeting room with some sort... Is this where he has his meetings about like videos and stuff? This is pretty sick!",
    "Why would you wanna jump in a toilet? That makes no sense!",
    "I was literally gonna break the law for video? You're just gonna steal candy from... I mean, that's pretty sick, but is that all this world is created for? Just for his video ideas?",
    "Oh gosh... I... I broke the painting! Oh no! Let me just... Oh... Oh gosh, that is not the same painting as it was before!",
    "He reads books? Really? I've never seen the kid touch a book in his life!",
    "What does this mean? Is this his diary? What is a video robot and he's saying he's gonna take over for him in his videos?",
    "You know what? He's probably just talking about like this new toy he got or something. I don't know, he's probably just roleplaying.",
    "Whoa, what is this? Oh, it's a secret room! Wait, this is awesome!",
    "Oh my goodness, it literally looks just like him except it has red eyes and blood everywhere!",
    "Is he trying to create a robot of himself that can record for him? That must be it! That explains everything!",
    "What the... Is that his robot? No, no, no! Hold on, hold on! I swear he was just here! What the... Wait, who the... What is happening?",
    "You know what, Mister Robot? It was nice meeting you! Tell him I said hi! I... I think I'm just gonna leave for now. You have a good time!",
    "Wait, what? I swear these doors were wood before! Where did the pressure plates go?",
    "Okay, okay, well, what is that robot doing there? Dude, you gotta chill out!",
    "Why would he put this in his house? Okay, okay, you know what? I'm doing the parkour! I... I am doing the parkour!",
    "Should not have stolen a USB... This is what I get!",
    "Oh my goodness! I'm a genius! What did I say? Lever! Boom! Let's yoink that and let's bring it over and put it on the red wool!",
    "The snake crawls across the board? What? That doesn't make any sense! A snake doesn't even crawl! Snake slithers like... like a snake and doesn't crawl like... not a snake? I don't know where I'm getting with this, guys.",
    "Oh my goodness! Robot! Really? He's always still following me! And is that a sword in his hand? Oh goodness!",
    "Yummy yummy yummy yummy! Go away spiders! Hey!",
    "Okay, okay! I'm about to die! I am about to die! I'm about to die!",
    "Two Ender Dragon heads guarding a door? Alright, that's perfectly normal for someone to have in their house! The decapitated heads of a dragon just standing there!",
    "Kids, this is called work harder not harder smarter... Wait, work smart... Oh wait, what? No, that's not a... Work smart no hard... That's expression... Look, I'm just gonna eat this Enchanted Golden Apple!",
    "Oh gosh! Is this a find a button? Oh my goodness! This kid really did the most!",
    "Why would you do that to me robot? I don't understand!",
    "Oh no! Is that... is that... is that... is that a pillager? Oh gosh!",
    "Robot... don't come closer! Why is he gonna be closer? Stop! Stop! Stop!",
    "The... yo! Are we out here? Ketchup brought out just for me!",
    "Oh yeah, about that... I've might have found your USB drive while I was over at your house and I might have just taken it because I was curious.",
    "Yeah, well, you also forgot to mention that it was a murderous robot! Yeah!",
    "Yeah, well, work on it better! And I wish I had to kill me!",
    "Wait, what? No, don't... don't come over! Don't come over! I'll... I'll get it to you back later!",
    "Oh gosh! Oh no! He left! Well, looks like I am in loads of trouble now because he is gonna get very, very mad!",
    "Well, at least we got to see what was in the USB drive! But if you did enjoy the video, click any of them on the screen right now to see more and also make sure to subscribe because it helps out a ton and you can always un... I advise on not doing that though. Okay, bye!"
]

##############################################################

original_samples = [
    "Oh my goodness, I can't believe I got lost again!",
    "I was literally just out for a little bit of a walk, and I guess I did real time far I've been walking because now I am stuck in the forest.",
    "It is so dark outside and there are so many legion trees here that I don't know how to get out.",
    "Oh my gosh, now there's even thunder!",
    "Well, I guess I'm just gonna have to find someone that lives around here and ask them for help.",
    "Oh, this is literally perfect! Maybe the person here can help me.",
    "Oh, that's super duper sad, but let's check out this house.",
    "There's even like cobwebs here and stuff, it must be super duper old.",
    "Oh no, oh no, this is super super bad and he's definitely not alive anymore.",
    "But am I supposed to report this to someone?",
    "Oh no, did I just step on this trip wire? Did that activate something?",
    "Am I gonna get stuck in a trap too?",
    "I can't take this anymore, I'm sorry, I'm on my way.",
    "Hello, hello mister... mister villager, why are your eyes like that?",
    "Oh no, this is giving me a super duper ultra bad feeling.",
    "Oh my goodness, what was that? That is way too creepy.",
    "Oh wait, this is a village! Oh maybe there's actually some villagers left, like this guy, but he's just super weird so he's not talking.",
    "Oh my goodness, that gave me a huge jump scare!",
    "He's stuck in another trap. Are you okay? Are you okay?",
    "And he's not responding. I think he may not be alive anymore.",
    "What is wrong with this place? No no no, this is super bad, this is super bad.",
    "Oh my goodness, what is all of this? What happened to all of the people here? Why are they all dead?",
    "Oh my goodness, why are there a bunch of dead humans stuck in here?",
    "No no no, is this village haunted or something? Or is there a murderer nearby?",
    "This is super duper ultra bad! Oh my gosh, I need to get out of here, I need to get out of here!",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Is he watching me? Hello, hello, can you watch me? Are you seeing me?",
    "Oh my goodness, I am so nervous. What is the evil villager gonna do to us?",
    "Like, what is around all of this? It just looks like a place where he does experiments or something.",
    "And oh my goodness, here is another guy that must have been trapped.",
    "Hello buddy, buddy are you okay? You gotta speak to me man, you gotta speak to me!",
    "Oh, 'run', that's all you can tell me?",
    "Oh no, I am so super nervous, very nervous now. This is bad, this is bad.",
    "And oh my goodness, this guy is huge! How did they ever capture him?",
    "And oh my goodness, look at his eyes and his teeth! Why does he look so scary?",
    "Oh my goodness, how did they do this to you? You're saying 'run' too?",
    "Why is everybody telling me to run? Well, probably because the evil villager is gonna like, kill me somehow.",
    "But still, this is so scary and he has even more people here. Look how terrified they look!",
    "And I'm so sorry guys, but I don't think I can escape with you. You guys are way too noisy and there's just too many people.",
    "So I have to do this by myself and there's a thing called a security... what's inside the security room?",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Literally nothing just happened, the camera just disappeared.",
    "But let's keep exploring and... oh, oh this is the torture chamber. Okay, I see, I see.",
    "So we need to figure out how to open the valve over here first and is there anything else this way?",
    "And whoa, there's a set of stairs here. Alright, let me go down over here.",
    "Is there anything here? Nope, I don't see anything.",
    "Here's the living... what is that? Is that... is that the evil villager?",
    "No no way, no way, no way! Wait, wait, there's a chest here and there's a bunch of stuff in here including a shield.",
    "Okay, let me equip that real quickly and... oh no no no no!",
    "Oh my god, he's right there, he's right there, he's right there!"
    "Oh my goodness, wait, this is actually so OP!",
    "This means I have to be super duper careful because pretty much a flower could kill me right now.",
    "Isn't that right, Mister Pig? He's just looking into the wall... Oh, there you go buddy. Oh, now his face is back in there.",
    "Wait, wait, did I do this wrong? Oh my goodness, it's one seed in four dirt!",
    "I thought it was the other way around! Oh, so we got all those seeds for nothing.",
    "I knew I shouldn't have beat up that pig.",
    "Oh my, it is... this is actually insane! I'm flying!",
    "I'm like kinda glitch flying though, but you know what? I'm still flying!",
    "What is this, the poop of Thanos? Do I have Thanos poop in my hands?",
    "Oh, you know what? We're gonna be able to find this super easily because I'm just gonna fly around!",
    "Oh, such a good idea! Let me just float straight up into this sky, like super high.",
    "Oh my goodness, I've been searching for this for so long! Hello, Missus Sugarcane, it's so very nice to meet you!",
    "Yo, I am fitted out! This means I don't only get superpowers, I also get super OP items!",
    "I just realized I'm like farting to fly. This is so funny!",
    "Oh gosh, no, no, no, no, no! Oh my goodness, oh my goodness! Please regenerate, regenerate, regenerate!",
    "I'm finding way more diamonds than I am coal right now. Wait, I see coal! I see coal!",
    "Oh my goodness, finally! I have never been this happy in my life to find coal before!",
    "Did I just get a golden apple? Oh my goodness, wait a minute, this is actually so OP!",
    "Wait, why do I have two souls of babies? Okay, okay, guys, yeah, give me a second. I'm trying to do something here.",
    "Gosh, it's so rude just interrupting me while I'm trying to record!",
    "Hey, everyone who was chasing me before, where you at? Oh yeah, look at that! Look at that guy, just disappeared!",
    "And holy moly guacamole! What is this?",
    "This can literally kill the Ender Dragon in one hit!",
    "Yeah! Oh, it just insta-kills everything! No matter what, I can literally spam click and just kill them!",
    "Oh my goodness, I can't fly in the Nether! This means I have to walk like a peasant!",
    "So we got all the nuggets. Chicken nuggets!",
    "Wait, why have I been scared? I have my abilities!",
    "Oh gosh, this is not gonna be as easy as I... But now we just gotta kill these blazes and...",
    "Come here, Mister Blazes! Give me your blaze rods!",
    "Fly away! Oh gosh, nope, nope, nope, nope! Not at all, not at all, not at all, not at all!",
    "It's literally just helping me get lazier and lazier! So I can fly and I can teleport!",
    "Oh my goodness, perfect! Thank you for spoiling me!",
    "How do you make a clock? Wait a minute, now I'm thinking about it, I literally don't know how to make a clock.",
    "Oh my goodness, the pain, the pain! But I'm also dropping a bunch of items.",
    "Please be redstone, drop me redstone! Drop me redstone, please!",
    "Oh my goodness, wait, they just disappear! Oh my goodness, this is so OP!",
    "They're probably so confused right now! Oh, look at this one! He's mad! He's mad that I took away his brothers!",
    "Don't worry, you'll be joining them! Oh gosh! Oh, that was hilarious!",
    "You know what? Never mind, the water ruined it for me. I just locked this up and...",
    "Oh, get out of here, mobs! Oh my goodness, yes! Where's the portal room? Where's this portal room?",
    "Please, portal room, where are you? Imagine the portal room actually responds! I... I'm right here!",
    "Wait, why? It's right here! Oh my goodness, what the heck? That's actually so unexpected!",
    "Come here, Ender Dragon! I'm coming for your body!",
    "And wait, this infinity bow is like... kinda sucks actually. It doesn't do that much damage.",
    "Oh, wait, I can't kill him! I gotta send him to the dark dimension! Come here, Mister End...",
    "Oh, wait, does it not work? Wait, where am I? What am I stuck in the obsidian?",
    "Oh my goodness, I literally teleported into the obsidian accidentally!",
    "I think we learned today that I should not be trusted with power.",
    "But that's it for today, and I will see you guys later!"
]

transcript_samples = [
    "Oh my goodness, I can't believe I got lost again!",
    "I was literally just out for a little bit of a walk, and I guess I did real time far I've been walking because now I am stuck in the forest.",
    "It is so dark outside and there are so many legion trees here that I don't know how to get out.",
    "What do I do?",
    "Oh my gosh, now there's even thunder!",
    "Well, I guess I'm just gonna have to find someone that lives around here and ask them for help.",
    "So maybe we can go this way and... wait a minute, I think I see a house!",
    "Oh, this is literally perfect! Maybe the person here can help me.",
    "Wait a minute, what is that? Is that a missing poster?",
    "Did a villager recently go missing or something?",
    "Oh, that's super duper sad, but let's check out this house.",
    "I don't think anybody's inside, I don't hear anyone and everything looks broken up.",
    "There's even like cobwebs here and stuff, it must be super duper old.",
    "But let's leave the house and... wait a minute, what is that?",
    "Who... my goodness, is that a human?",
    "What happened to him? Buddy, are you okay?",
    "Oh my goodness, why did this happen to you?",
    "Oh no, oh no, this is super super bad and he's definitely not alive anymore.",
    "But am I supposed to report this to someone?",
    "I mean, there's a dead human in the forest but... oh my goodness, this is... wait a minute, why is there a bunch of traps set up?",
    "Oh no, did I just step on this trip wire? Did that activate something?",
    "Am I gonna get stuck in a trap too?",
    "Oh no no, this is way too creepy. I'm so sorry, I'll come back for you later and report you to someone.",
    "I have to get out of here now, this is so scary!",
    "I can't take this anymore, I'm sorry, I'm on my way.",
    "I have to get back home for now, that is super duper creepy.",
    "I need to figure out how to get out of this forest as fast as... wait a minute, is that a villager?",
    "What is he doing? That is super duper creepy.",
    "But there's another house here, and there's nothing here but it's all broken up too.",
    "But why is there a villager over here? Should I go say hi to him?",
    "Hello, hello mister... mister villager, why are your eyes like that?",
    "Oh no, this is giving me a super duper ultra bad feeling.",
    "You know what? You stay in there, I'm gonna go explore the places and learn how to get out of here, so bye!",
    "Oh my goodness, what was that? That is way too creepy.",
    "And here's another broken house. Why is everything that's broken in this place?",
    "Oh wait, this is a village! Oh maybe there's actually some villagers left, like this guy, but he's just super weird so he's not talking.",
    "So I'm gonna keep going down over here and hopefully we can find some villagers left and... who... oh my goodness!",
    "Oh my goodness, that gave me a huge jump scare!",
    "Oh my gosh, like I came out of nowhere! What the heck was that?",
    "He's stuck in another trap. Are you okay? Are you okay?",
    "And he's not responding. I think he may not be alive anymore.",
    "What is wrong with this place? No no no, this is super bad, this is super bad.",
    "You just stay there for now and... oh my goodness, what is all of this?",
    "What happened to all of the people here? Why are they all dead?",
    "This guy's head is literally on a stick! Oh my god, that's way too scary.",
    "And there's a bunch of blood everywhere. Oh no no, and what's in this?",
    "Oh my goodness, why are there a bunch of dead humans stuck in here?",
    "No no no, is this village haunted or something? Or is there a murderer nearby?",
    "This is super duper ultra bad! Oh my gosh, I need to get out of here, I need to get out of here!",
    "And I think this is the way out. Yes, yes! Okay, let me go here and... oh my goodness, that village is way too haunted.",
    "I need to get... oh my goodness, it isn't over!",
    "Why are there more dead humans here? And it's a gate to a castle-looking thing, or is that a house?",
    "Does the person that's living here know that there's a bunch of dead humans out here?",
    "But maybe I can get help from the person inside that house and get out of this forest.",
    "So you know what? Let me go through here and... wait a minute, why can I not go in?",
    "Excuse me, excuse me, can you let me in?",
    "Oh wait a minute, there's a keyhole here. Maybe I have to find a key to open it.",
    "Well, I'll go explore and try to find the key, but I don't wanna go too far because who knows what might be around here.",
    "What could have happened to all of these villagers to make them like that?",
    "But wait, this is another broken house and there's another chest in here.",
    "Don't mind if I do and... whoa, there's a bunch of rot and flesh here, more bones, and a wooden sword.",
    "That's gonna come in handy, and a fiddlestick and vermar? What is that? I have no idea.",
    "But at least I have a sword that will help me defend against others.",
    "But I haven't found the key yet, so I might have to go in the other direction, explore it that way to see if there's a key.",
    "Oh my goodness, this gets more scary every time I look at it.",
    "So hello, is there a key in here? There's a furnace, nothing in there.",
    "Can I go inside here? No, I can't fit.",
    "Where is this key? That road is blocked off, that road is blocked off and... wait a minute, there's another chest here!",
    "Maybe it's inside here. Let's look and... yes! I have a key along with some more rotted flesh and some wheat.",
    "This is perfect and it can be placed on a carved pumpkin.",
    "And what is all of this stuff? What is all of this for?",
    "I don't know, maybe they'll come in handy later, but at least I have a key to go inside.",
    "And I really really hope that the person inside living that house could help me because this is not what I signed up for.",
    "I am just lost, I just wanna go home.",
    "So I really hope I can leave and... there we go, the key has been placed and now I can go through and... oh my goodness, I feel much better now.",
    "Wait a minute, what is that? Uh-uh, who is that?",
    "Don't make any noise... wait a minute, what the heck just happened?",
    "It just zoomed in on a little villager over there and it looks like he was cooking something.",
    "I just got a warning that said don't make any noise. What does that mean? What does that mean?",
    "I am so super duper scared and... oh my goodness, oh my goodness, which way do I go? Which way do I go?",
    "Oh, I take back everything I said. I feel super duper bad now.",
    "Oh my goodness, I have a really bad feeling about this and... oh no, was that the doorbell?",
    "Was that... oh no, oh no, whatever did the villager that was just there... oh no, I didn't mean to!",
    "Oh my goodness, we gotta run, run!",
    "Oh my goodness, what's happening? What's happening? Why am I getting told to run? Why am I getting told to run?",
    "No no no no, I didn't mean to press that doorbell!",
    "Oh my gosh, it says to run, it says to run! Why am I running? Where am I running off to?",
    "No no no no, I need to get out of here!",
    "My goodness, let me run and... what? Wait, what? Why am I trapped in here?",
    "What the heck? Are you feeling sick? No no no, this is bad, please please!",
    "The villager... oh no, oh no, what's happening? What is happening?",
    "Oh my goodness, oh my goodness, I feel super... oh no, oh no, oh no!",
    "What is that? What is that? Where am I? Am I locked inside of a cage?",
    "Wait, what the heck just happened? I just blacked out and now I'm inside here!",
    "Oh my goodness, no no, how do I get out? If you're... this is terrible!",
    "That evil villager... oh my goodness, oh my goodness, everything is scaring me right now!",
    "That villager literally just trapped me and he brought me inside here.",
    "No no, I'm just trying to get back home and of course I get caught by this weird evil villager.",
    "I thought he could have helped me but he must be the one that killed all of those other innocent villagers.",
    "And there's a bunch of doors here. Can I open them? No I can't, but there's a chest here too.",
    "And there's a diary inside along with some steak and a wooden axe.",
    "Let me read this diary and... what does it say?",
    "It looks like a diary made by a guy named Victor and he left us instructions on how to escape this place.",
    "And based on what I'm reading, I pretty much need to blow up a thing called a boiler room so I can escape through that.",
    "But to do that, I have to open six valves so I'll build up pressure in the boiler room so it explodes.",
    "So our mission right now is to open these six valves and the first valve I have to get to is a place called the torture chamber valve.",
    "Oh my gosh, that sounds super duper scary, but what does this lever do right here?",
    "Let's flick this and... oh, here we go!",
    "The torture chamber valve has been opened, which is good news but it's also bad news because I do not want to go into a thing called the torture chamber.",
    "And oh my goodness, what is all of this stuff? Can I squeeze through here and... yes I can!",
    "Alright, but where do I go from here? And there's a security camera over there.",
    "Is he watching me? Hello, hello, can you watch me? Are you seeing me?",
    "Oh my goodness, I am so nervous. What is the evil villager gonna do to us?",
    "Like, what is around all of this? It just looks like a place where he does experiments or something.",
    "But wait a minute, a dungeon? Why does he have a dungeon in his house?",
    "And oh my goodness, is that a person? He keeps people in his dungeon!",
    "And oh my goodness, here is another guy that must have been trapped.",
    "Hello buddy, buddy are you okay? You gotta speak to me man, you gotta speak to me!",
    "Oh, 'run', that's all you can tell me?",
    "Oh no, I am so super nervous, very nervous now. This is bad, this is bad.",
    "And oh my goodness, this guy is huge! How did they ever capture him?",
    "And oh my goodness, look at his eyes and his teeth! Why does he look so scary?",
    "Oh my goodness, how did they do this to you? You're saying 'run' too?",
    "Why is everybody telling me to run? Well, probably because the evil villager is gonna like, kill me somehow.",
    "But still, this is so scary and he has even more people here. Look how terrified they look!",
    "Is there any way I can escape through this place? No, there's nothing here, nothing in this dungeon cell either.",
    "There's nothing in here too. Well, what could there be to help me escape?",
    "And I'm so sorry guys, but I don't think I can escape with you. You guys are way too noisy and there's just too many people.",
    "So I have to do this by myself and there's a thing called a security... what's inside the security room?",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Hello? Literally nothing just happened, the camera just disappeared.",
    "Well, I'll just figure that out later. Maybe the cameras just aren't in function or something.",
    "But let's keep exploring and... oh, oh this is the torture chamber. Okay, I see, I see.",
    "So we need to figure out how to open the valve over here first and is there anything else this way?",
    "And whoa, there's a set of stairs here. Alright, let me go down over here.",
    "Is there anything here? Nope, I don't see anything.",
    "Here's the living... what is that? Is that... is that the evil villager?",
    "No no way, no way, no way! Wait, wait, there's a chest here and there's a bunch of stuff in here including a shield.",
    "Okay, let me equip that real quickly and... oh no no no no!",
    "Oh my god, he's right there, he's right there, he's right there!",
    "No problem, so stop stop stop stop! Okay, can I get him? Can I kill him?"
]

transcript_samples2 = [
    "There's custom infinity hearts in Minecraft.",
    "The my zone heart can make me fly in the air and levitate.",
    "The time zone heart can make me set enemies into the literal dark dimension.",
    "Once I have all the infinity hearts, I can... well, you'll have to see that for yourselves.",
    "Wait, where's all my hearts? Oh yeah, I forgot I just have one giant heart.",
    "That is one hardly looking heart.",
    "If I take damage... Oh gosh, I do not have any health at all.",
    "This means I have to be super duper careful because pretty much a flower could kill me right now.",
    "Isn't that right, Mister Pig? He's just looking into the wall... Oh, there you go buddy. Oh, now his face is back in there.",
    "This is a kartik I'm getting rid of it, but I also spotted with this guidebook.",
    "Oh, is that what the infinity heart's gonna look like? That is actually awesome.",
    "Those should all give me different powers.",
    "The first heart should be the mine heart. Look up to fly and sneak in the air to boost.",
    "Wait, what? It's the first fragment of the heart and we can hardly fly? This is awesome!",
    "So we just need one piece of dirt and four seeds.",
    "Give me all the seeds! Give me all the seeds!",
    "Why are there literally no seeds dropping?",
    "Oh gosh, is that a pig? Hello there, give me your seeds Mister Piggy!",
    "Oh, he actually just pooped it out. Perfect!",
    "We just need one more now, and boom! We got the four seeds.",
    "Let's just grab some wood now to make a crafting table.",
    "I wonder if I get the entire heart, then I could just like destroy worlds in an instant.",
    "Like, if I snap my fingers, is everything just gonna collapse? I don't know, we'll see.",
    "Alright, we got wood so let's make that into a beautiful crafting table.",
    "Now it should be one dirt in the middle and the four seeds across... Why isn't it working?",
    "Wait, wait, did I do this wrong? Oh my goodness, it's one seed in four dirt!",
    "I thought it was the other way around! Oh, so we got all those seeds for nothing.",
    "I knew I shouldn't have beat up that pig.",
    "Okay, so four dirt just like that and a seed in the middle and boom! We got the mine heart!",
    "We can look up to fly and sneak in the air to boost... or if I look up, am I flying? I'm not flying.",
    "Wait, do I have to... do I have to sneak up? Oh my goodness, wait, hold up, how did I just do that?",
    "Okay, so I look up and... and then I sneak, is that what would happen? I'm so confused.",
    "Do I have to jump first or... Oh, okay, I see. Now it's working, now it's working!",
    "I have to jump first and then I look up. Oh my, it is... this is actually insane! I'm flying!",
    "I'm like kinda glitch flying though, but you know what? I'm still flying!",
    "Wait a minute, I can glide in the air too! Oh, that's actually awesome!",
    "This literally means I can never take fall damage again!",
    "Hold on, when I crafted the heart, I also got these four purple thingies. It's called thanosight.",
    "What is this, the poop of Thanos? Do I have Thanos poop in my hands?",
    "Well, let's check out what the next heart is. It's the power heart, and it gives you strength and speed on taking damage.",
    "I need four gravestones and one sugar. You know what? That is not hard at all, I will take that!",
    "Let me just break this crafting table, yank, and I guess we need to go mining.",
    "So first things first, let's go grab some more wood. The tree is so far, but you know what? I can fly there! Yes!",
    "But there's much cooler ones in this heart, so I'm excited!",
    "Okay, we got all the woods, so now we're just gonna make ourselves a nice little pickaxe.",
    "Now we just go digging for the cobblestone and... wait, it was four cobblestone, one sugar, not the other way around!",
    "Oh, where am I gonna go find sugar? To find one of those bamboo-looking thingies... What is it called again? Is it sugarcane?",
    "I have to go find sugarcane. Haven't been playing Minecraft for this long and still not know what sugarcane is!",
    "While we're here, let's just grab a bunch of coal so we can make ourselves a full set of tools real quick.",
    "Alright, should be good. Let me head back up and now I'm gonna make myself a pickaxe.",
    "I'm also gonna make myself a sword. Let me also make myself an axe, just like that.",
    "Now we have to go find some sugarcane, but that's gonna be next to sand, so maybe like a beachy area?",
    "Oh, you know what? We're gonna be able to find this super easily because I'm just gonna fly around!",
    "Oh, such a good idea! Let me just float straight up into this sky, like super high.",
    "I'm just gonna let it glide everywhere, then I'm gonna be able to find it so easily!",
    "Alright, now let's just... Okay, you know what? That did not work at all.",
    "Oh, and wait! Wait! I see sugarcane! I see the sugarcane! Let me go grab that real quick!",
    "Oh my goodness, I've been searching for this for so long! Hello, Missus Sugarcane, it's so very nice to meet you!",
    "Here we are, sugarcane! Oh, thank you so much, pleasure doing business with you!",
    "So now we just pop this in here, we should get our eight sugar, and let's just surround this with cobblestone to get our power heart!",
    "Oh, and now if we take damage, it should give us strength and speed.",
    "It also gave us more thanosight. I'm not sure what this is. Maybe I can craft stuff with it?",
    "Like, can I craft leggings or... Oh my goodness, wait, I actually can! Oh love!",
    "Oh my goodness, Protection V! Wait, this is actually so OP! Let me just put that on.",
    "Yo, I am fitted out! This means I don't only get superpowers, I also get super OP items!",
    "So let's see what it can make. I'm really excited to see the sword, they might be insanely overpowered.",
    "But that means we have to get more hearts. And speaking of hearts, let's see what this power heart does.",
    "Let me take some fall damage real quick and... Oh my goodness, I... I completely forgot I can't even take damage!",
    "How do I die? Wait... Okay, what if I just go in the water and run out of breath? Now we gotta wait.",
    "Alright, let's see. I took damage and... Okay, okay, and give a Strength V and Speed II and Regeneration... Duration?",
    "Oh my goodness, wait, that is actually so overpowered! But it runs out real quickly.",
    "Okay, I mean that's pretty okay though for fighting a bunch of mobs.",
    "What's the next heart? Let's see. It's the reality heart, and it spawns random items on taking damage.",
    "We need four iron and one coal to make it. And that means... Oh, we need to go mining!",
    "And mining means a lot of monsters, but thankfully I got the power heart there to help me out.",
    "So let's go find a cave. Up, up, way and beyond!",
    "I just realized I'm like farting to fly. This is so funny!",
    "Oh, okay, I found a really nice looking cave right here. So let's drop in and... Okay, let's go find some iron.",
    "Oh, there's iron! Oh, there's a creeper right there! That is a creeper! They get... Oh gosh, no! No! Iron! He really does blow up my iron! Really?",
    "Okay, well, we found some iron here, so let's just grab all of this real quickly.",
    "And now let's just dig down. I'm gonna see if I can find some more iron, just in case.",
    "And I also need to make myself some basic armor, even though I do have the super OP Thanos-ite leggings.",
    "Is there any more iron here? I haven't found some in a long time and... Wait!",
    "Oh my goodness, wait, this place is huge! And okay, that's another creeper!",
    "Alright, chill bro, chill, chill, chill! Okay, okay, calm down, calm down!",
    "I have to remember, even though I am OP, I have really little hearts, so this could end up really bad.",
    "Alright, safely got rid of it, and there looks to be more iron... Oh gosh, no, no, no, no, no!",
    "Oh my goodness, oh my goodness! Please regenerate, regenerate, regenerate!",
    "I almost just died to lava! Oh, and I don't have any food too!",
    "And oh gosh, there's so many mobs here! Oh gosh, okay, okay, we gotta try to kill them. Come on, die, die!",
    "Wait, they're actually dying in one shot though, which is really helpful!",
    "No, stop it! Oh, diamonds! Wait, diamonds! I don't have a pickaxe to get it though!",
    "No, gonna dodge all these guys! Get away, zombie! I'm gonna fly away!",
    "Alright, we're safely on the other side. Let me just grab some cobblestone to like, block myself in real quick because these mobs are actually gonna end up killing me.",
    "And now that we got our iron, let's make a furnace and smelt it real quickly.",
    "We got our four iron, so now let's just place this around like this and place our cobblestone... Wait, hold up, did I get the recipe wrong again?",
    "Oh gosh! Oh, okay, okay. So one coal, that's all we need. So let's go grab that real quick.",
    "Oh gosh, some mobs are shooting at me again already! Please, I just need one piece of coal! That's it, that's it!",
    "How is there no coal? I see more diamonds than I see coal!",
    "Oh, wait, there's coal! It... No, there's not. There's literally no coal. How is this possible?",
    "Oh my goodness, we came all the way to like a different underground dimension to find this coal, and there's still more diamonds!",
    "I'm finding way more diamonds than I am coal right now. Wait, I see coal! I see coal!",
    "Oh my goodness, finally! I have never been this happy in my life to find coal before! Usually it's just like way too much and I wanna get rid of it.",
    "But there we go, we got our one coal, and we gotta make another crafting table since we lost our other one.",
    "So let's surround this iron and boom! Reality heart! And it spawns random items on taking damage.",
    "That should be pretty cool because there's a bunch of mobs right here waiting to kill me.",
    "And I only got one Thanos-ite this time, so I can't make the sword quite yet, but let's see what these babies do!",
    "Come here, Mister! Come here! They're attacking me! Yes! And... Oh, wait, it's actually dropping random items!",
    "Hold on, hold on, wait, this is good! This actually... Okay, okay, you know what? Maybe that's a little bit too much.",
    "Did I just get a golden apple? Oh my goodness, wait a minute, this is actually so OP!",
    "This is the best one so far! I just have to be super duper careful that it doesn't actually kill me because I don't have like a lot of hearts right now.",
    "Alright, yes! Keep dropping good stuff! Oh, bunny! I'll take the cold booty!",
    "And okay, okay, that's good, that's good. You're... you're good, bro. It's all good.",
    "Wait a minute, what did I just drop? And what is this? Is this a... It dropped a soul!",
    "Wait, why do I have two souls of babies? Okay, okay, guys, yeah, give me a second. I'm trying to do something here. Gosh, it's so rude just interrupting me while I'm trying to record!",
    "Okay, let's take a look at this thing. Oh my goodness, that looks crazy cool!",
    "Does that have any special powers? I can't do anything with it. Wait, let's check the guidebook. Maybe it'll say something about it.",
    "Okay, it shows up here and it's a soul heart. Hit mobs to get special effects. Mobs drop souls.",
    "Oh, okay, so we gotta use this to craft our next part of the heart. That makes sense.",
    "But first things first, let's actually get completely looted up because we're gonna be taking a lot of damage and I don't wanna die.",
    "So let's make ourselves a full set of iron armor too. But let me eat this cake first. No, no, so much better already!",
    "Okay, time to go mining. You know what? While we're getting iron, let's just go grab our diamond too because there is just way too many to pass up.",
    "So let's just grab these bad boys real quick, and we should have enough of everything.",
    "So let's go back to our furnace and smelt these guys.",
    "Alright, let's make ourselves some iron armor. There we go and... Oh my goodness, we are fitted out!",
    "We can literally take on anything now! But now that that's done, let's go grab two more souls just so we can make our next heart.",
    "So let's kill this guy and let's kill this guy, and that should be enough.",
    "And wait a minute, what did it just drop? Did it just give me a diamond sword? This is enchanted too! That's awesome!",
    "Alright, there's a lot of mobs here. Let's get out of here!",
    "Okay, we're back and now we just need a glass bottle. And thankfully, we did get a bunch of potions just now.",
    "I got a Potion of Haste III and a Potion of Leaping. So let's drink this potion, we have a glass bottle.",
    "And now we put that in the middle and put the souls like this... We get the soul heart!",
    "And hitting mobs will give potion effects! Yes, this is awesome! I'm literally so overpowered!",
    "Hey, everyone who was chasing me before, where you at? Oh yeah, look at that! Look at that guy, just disappeared!",
    "He doesn't... They do not want to mess with me. They are just disappearing. Wait, why are they actually disappearing?",
    "Okay, let's go find them. Come here, everyone! Don't... Come here!",
    "Oh my goodness, it just gives me a bunch of random effects! Wait a minute, what? It gives me bad effects too!",
    "I have Hunger III, but I also have Saturation III. So how does that work exactly?",
    "Oh, you know what? I'm not asking you. Let's just kill these guys. Don't die, everyone here!",
    "And they're all dead! Oh my goodness, that was the most obvious thing I've ever seen!",
    "But now that I also look at it, I have three more Thanos-ites. So this means I could make a Thanos-ite sword!",
    "And with the... Oh my goodness, really? These mobs are so rude!",
    "Oh, wait, can I make a Thanos-ite axe? Is that also a thing?",
    "Okay, no, that's not a thing. But a sword is a thing, and holy moly guacamole!",
    "What is this? I'm gonna throw this diamond sword away because obviously this... My gosh!",
    "Two hundred percent knockback resistance, one hundred percent speed, and one thousand attack damage!",
    "This can literally kill the Ender Dragon in one hit!",
    "Getting the rest of the hearts is gonna be so easy thanks to this.",
    "So let's see what the next one is. It's the space heart, and you need four gold and an ender pearl to make it.",
    "Alright, that doesn't seem that bad. All of that should be in the Nether.",
    "And we have to go there anyway for the blaze rods, so let's go back to the surface and find a lava pool real quickly.",
    "Home sweet home! No mobs, just little piggies.",
    "And wait, I kinda wanna test out the infinity sword real quick. Are you sure about that?",
    "Yeah! Oh, it just insta-kills everything! No matter what, I can literally spam click and just kill them! This is so... Alright, let's go find a lava pool.",
    "Where that, where that... Oh, there it is! Found one, perfect!",
    "So let's grab the water bucket and just make the portal real quickly. Boom, popping, boom boom boom boom!",
    "Thank you ma'am, bop bye bye, bing bing bing, pow! Let's light this baby up and let's go inside.",
    "Oh gosh, ready to respond! Let me fly up there real quickly and... Wait, wait a minute, what?",
    "I can't even fly anymore! Hold on, am I glitching?",
    "Oh my goodness, I can't fly in the Nether! This means I have to walk like a peasant!",
    "Oh, wait, what the... Why did I just randomly start floating? Wait, what? What is happening? Why am I flying now?",
    "Okay, I guess that far move doesn't work, but I guess I still levitate when I look up. I mean, it's better than nothing.",
    "So we need four gold, so I'm just gonna steal these guys because it's the easiest way to go.",
    "And then we also need an ender pearl, and hopefully we can find that at the fortress or find an Enderman on the way there.",
    "So we got all the nuggets. Chicken nuggets!",
    "And now we gotta find the fortress real quickly and... Oh, I found it! I found it! I found it! Yes, let's go!",
    "And oh, wait, I could fly again too! Okay, perfect! One great thing after another!",
    "And oh my goodness, that is a lot of wither skeletons!",
    "Wait, why have I been scared? I have my abilities! What... Wait a minute, it doesn't kill them right away on one shot?",
    "But this is a thousand attack damage! How is this possible? I literally got scammed!",
    "Oh gosh, this is not gonna be as easy as I... But now we just gotta kill these blazes and... Okay, these guys are mad at me.",
    "Let's grab that and... Block of diamond? I'll take that gladly!",
    "Oh gosh, okay, let's just keep killing all of these guys. Come here, Mister Blazes! Give me your blaze rods!",
    "Okay, I should have enough. Let's just get out of here now because these guys are really hacking on me.",
    "Fly away! Oh gosh, nope, nope, nope, nope! Not at all, not at all, not at all, not at all!",
    "Okay, but my fly journey just kinda failed there. But we also need to get an ender pearl.",
    "But let's just do it in the overworld because this is just way too scary still.",
    "And to home we go! Okay, we're back. Let's go find some Endermen now.",
    "And wait, wait a minute, what? Wait, how do I have six ender pearls?",
    "Oh, it must have been one of those random items I dropped! You know what? That's actually perfect!",
    "Now we don't have to go fight an Enderman too, and this means we can make the next heart right away!",
    "So let's make another crafting table, and it was four gold like this and one ender pearl in the middle to get the space heart.",
    "And uh-oh gosh, sneak right-click to teleport in the direction you face!",
    "And I literally like it better than... Wait, this is better than flying! Flying, I still have to move, but now I don't even have to move!",
    "It's literally just helping me get lazier and lazier! So I can fly and I can teleport! Oh my goodness, perfect! Thank you for spoiling me!",
    "And now we can also head to the End portal to get to the Ender Dragon and beat the game.",
    "But we do have one more heart, and that is the time heart, which is four redstone and one clock.",
    "How do you make a clock? Wait a minute, now I'm thinking about it, I literally don't know how to make a clock.",
    "How to make clock... Oh, it's four gold and one redstone! That shouldn't be too bad.",
    "We already have the gold. Now we just need the redstone.",
    "And instead of going back into a cave to get it, I think I have a better idea.",
    "Oh my goodness, the pain, the pain! But I'm also dropping a bunch of items. Please be redstone, drop me redstone!",
    "Drop me redstone, please! It literally dropped me another right enchanted helm, but no redstone yet.",
    "And wait, it also dropped me another right helmet! Oh gosh, okay, I'll... I'll take that.",
    "Wait, wait! Drop redstone! Drop redstone! Yes! Come on! Oh my goodness, please be enough!",
    "And we have... How much redstone? Six redstone! Okay, that's perfect! That's actually perfect!",
    "I can finally make the last heart! So we gotta make a clock first, and then we're gonna surround the clock with redstone to get the time heart.",
    "And oh my goodness, wait, what did this give me? It gave me an infinity bow, which looks absolutely awesome!",
    "Oh, and it shoots flaming arrows! Is that sick!",
    "And what else? Right-click while looking at a mob to send them to dark dimension? To dark dimension? What?",
    "Let me try it on these mobs real quick. Okay, so if I just look at a mob and then I right-click on them...",
    "Oh my goodness, wait, they just disappear! Oh my goodness, this is so OP!",
    "I can literally just get rid of them instantly! They don't die because they don't drop anything, but they get sent to the dark dimension!",
    "They're probably so confused right now! Oh, look at this one! He's mad! He's mad that I took away his brothers!",
    "Don't worry, you'll be joining them! Oh gosh! Oh, that was hilarious!",
    "Wait, that means I can technically beat the Ender Dragon in one second!",
    "But before we go and try that out, let me also make some more armor with Thanos-ite.",
    "I'm gonna get the Thanos-ite chestplate. Oh, thank you! Give me that!",
    "And I also make myself some gold booties, and I am ready to take on the Ender Dragon!",
    "So which direction is it? That way? Okay, perfect! Let's go find the fortress!",
    "Do this again and... Wait, it went straight into the ground this time? Okay, okay, we're right above the stronghold now.",
    "We just gotta dig straight down. Let me drink my Haste potion to make this go faster.",
    "You know what? Never mind, the water ruined it for me. I just locked this up and... Oh, we made it! Yes, we made it!",
    "Oh, get out of here, mobs! Oh my goodness, yes! Where's the portal room? Where's this portal room?",
    "Please, portal room, where are you? Imagine the portal room actually responds! I... I'm right here!",
    "Wait, why? It's right here! Oh my goodness, what the heck? That's actually so unexpected!",
    "Maybe it actually was able to hear me! But now we got it all set up, so let's just... Alright, can you chill? Can you chill?",
    "But before so rudely interrupted, I was saying... Come here, Ender Dragon! I'm coming for your body!",
    "Let's just fly up now and... Where's the Ender Dragon? Where's that big guy?",
    "Okay, I don't see him right now, but you know what? Let's just break all these end crystals.",
    "Oh, wait, there he is! There he is! Come here, Mister Ender Dragon! Come here!",
    "And wait, this infinity bow is like... kinda sucks actually. It doesn't do that much damage.",
    "But whatever, let's just break all of the crystals over there. There we go, they're all gone now.",
    "And oh, he's punching! He's punching! Okay, come on, infinity sword, infinity sword!",
    "No! Broke! Keeps hitting me, but... Oh, wait, wait, wait! How much damage... He's literally almost dead!",
    "Oh, wait, I can't kill him! I gotta send him to the dark dimension! Come here, Mister End... Oh, wait, does it not work?",
    "Wait, where am I? What am I stuck in the obsidian? Oh my goodness, I literally teleported into the obsidian accidentally!",
    "Oh my goodness! Okay, wait, can I... can I teleport out? Oh, yes, I did it! Okay, I did it!",
    "Wait, so this dark dimension thing... And I'll work on it, or am I just missing...",
    "Alright, let's wait for him to perch one more time and see if it actually works or not.",
    "Hours later... Oh, okay, he's perching! He's perching! Dark dimension, go! Go to the... go to the dark dimension!",
    "He... he's not going to the dark dimension! Oh gosh! Okay, it doesn't need to work on him. I'm just gonna have to kill him with the infinity bow.",
    "Come on, Hawkeye! Yeah! So he did it! Oh my goodness, finally!",
    "I'm still mad though that the dark dimension didn't work. You know what? You go to the dark dimension!",
    "Yeah, you go to the dark dimension! I'm releasing all my anger on you guys! Go to the dark dimension, everyone here!",
    "I think we learned today that I should not be trusted with power.",
    "But if you guys want another video, click any of them on the screen right now!",
    "And also make sure to subscribe! If you do, I'll give you a cookie!",
    "But that's it for today, and I will see you guys later! Poost!"
]