selected_transcript_samples = [
    "Oh my goodness, I can't believe I got lost again!",
    "I was literally just out for a little bit of a walk, and I guess I did real time far I've been walking because now I am stuck in the forest.",
    "It is so dark outside and there are so many legion trees here that I don't know how to get out.",
    "Oh my gosh, now there's even thunder!",
    "Well, I guess I'm just gonna have to find someone that lives around here and ask them for help.",
    "Oh, this is literally perfect! Maybe the person here can help me.",
    "Oh, that's super duper sad, but let's check out this house.",
    "There's even like cobwebs here and stuff, it must be super duper old.",
    "Oh no, oh no, this is super super bad and he's definitely not alive anymore.",
    "But am I supposed to report this to someone?",
    "Oh no, did I just step on this trip wire? Did that activate something?",
    "Am I gonna get stuck in a trap too?",
    "I can't take this anymore, I'm sorry, I'm on my way.",
    "Hello, hello mister... mister villager, why are your eyes like that?",
    "Oh no, this is giving me a super duper ultra bad feeling.",
    "Oh my goodness, what was that? That is way too creepy.",
    "Oh wait, this is a village! Oh maybe there's actually some villagers left, like this guy, but he's just super weird so he's not talking.",
    "Oh my goodness, that gave me a huge jump scare!",
    "He's stuck in another trap. Are you okay? Are you okay?",
    "And he's not responding. I think he may not be alive anymore.",
    "What is wrong with this place? No no no, this is super bad, this is super bad.",
    "Oh my goodness, what is all of this? What happened to all of the people here? Why are they all dead?",
    "Oh my goodness, why are there a bunch of dead humans stuck in here?",
    "No no no, is this village haunted or something? Or is there a murderer nearby?",
    "This is super duper ultra bad! Oh my gosh, I need to get out of here, I need to get out of here!",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Is he watching me? Hello, hello, can you watch me? Are you seeing me?",
    "Oh my goodness, I am so nervous. What is the evil villager gonna do to us?",
    "Like, what is around all of this? It just looks like a place where he does experiments or something.",
    "And oh my goodness, here is another guy that must have been trapped.",
    "Hello buddy, buddy are you okay? You gotta speak to me man, you gotta speak to me!",
    "Oh, 'run', that's all you can tell me?",
    "Oh no, I am so super nervous, very nervous now. This is bad, this is bad.",
    "And oh my goodness, this guy is huge! How did they ever capture him?",
    "And oh my goodness, look at his eyes and his teeth! Why does he look so scary?",
    "Oh my goodness, how did they do this to you? You're saying 'run' too?",
    "Why is everybody telling me to run? Well, probably because the evil villager is gonna like, kill me somehow.",
    "But still, this is so scary and he has even more people here. Look how terrified they look!",
    "And I'm so sorry guys, but I don't think I can escape with you. You guys are way too noisy and there's just too many people.",
    "So I have to do this by myself and there's a thing called a security... what's inside the security room?",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Literally nothing just happened, the camera just disappeared.",
    "But let's keep exploring and... oh, oh this is the torture chamber. Okay, I see, I see.",
    "So we need to figure out how to open the valve over here first and is there anything else this way?",
    "And whoa, there's a set of stairs here. Alright, let me go down over here.",
    "Is there anything here? Nope, I don't see anything.",
    "Here's the living... what is that? Is that... is that the evil villager?",
    "No no way, no way, no way! Wait, wait, there's a chest here and there's a bunch of stuff in here including a shield.",
    "Okay, let me equip that real quickly and... oh no no no no!",
    "Oh my god, he's right there, he's right there, he's right there!"
]

transcript_samples = [
    "Oh my goodness, I can't believe I got lost again!",
    "I was literally just out for a little bit of a walk, and I guess I did real time far I've been walking because now I am stuck in the forest.",
    "It is so dark outside and there are so many legion trees here that I don't know how to get out.",
    "What do I do?",
    "Oh my gosh, now there's even thunder!",
    "Well, I guess I'm just gonna have to find someone that lives around here and ask them for help.",
    "So maybe we can go this way and... wait a minute, I think I see a house!",
    "Oh, this is literally perfect! Maybe the person here can help me.",
    "Wait a minute, what is that? Is that a missing poster?",
    "Did a villager recently go missing or something?",
    "Oh, that's super duper sad, but let's check out this house.",
    "I don't think anybody's inside, I don't hear anyone and everything looks broken up.",
    "There's even like cobwebs here and stuff, it must be super duper old.",
    "But let's leave the house and... wait a minute, what is that?",
    "Who... my goodness, is that a human?",
    "What happened to him? Buddy, are you okay?",
    "Oh my goodness, why did this happen to you?",
    "Oh no, oh no, this is super super bad and he's definitely not alive anymore.",
    "But am I supposed to report this to someone?",
    "I mean, there's a dead human in the forest but... oh my goodness, this is... wait a minute, why is there a bunch of traps set up?",
    "Oh no, did I just step on this trip wire? Did that activate something?",
    "Am I gonna get stuck in a trap too?",
    "Oh no no, this is way too creepy. I'm so sorry, I'll come back for you later and report you to someone.",
    "I have to get out of here now, this is so scary!",
    "I can't take this anymore, I'm sorry, I'm on my way.",
    "I have to get back home for now, that is super duper creepy.",
    "I need to figure out how to get out of this forest as fast as... wait a minute, is that a villager?",
    "What is he doing? That is super duper creepy.",
    "But there's another house here, and there's nothing here but it's all broken up too.",
    "But why is there a villager over here? Should I go say hi to him?",
    "Hello, hello mister... mister villager, why are your eyes like that?",
    "Oh no, this is giving me a super duper ultra bad feeling.",
    "You know what? You stay in there, I'm gonna go explore the places and learn how to get out of here, so bye!",
    "Oh my goodness, what was that? That is way too creepy.",
    "And here's another broken house. Why is everything that's broken in this place?",
    "Oh wait, this is a village! Oh maybe there's actually some villagers left, like this guy, but he's just super weird so he's not talking.",
    "So I'm gonna keep going down over here and hopefully we can find some villagers left and... who... oh my goodness!",
    "Oh my goodness, that gave me a huge jump scare!",
    "Oh my gosh, like I came out of nowhere! What the heck was that?",
    "He's stuck in another trap. Are you okay? Are you okay?",
    "And he's not responding. I think he may not be alive anymore.",
    "What is wrong with this place? No no no, this is super bad, this is super bad.",
    "You just stay there for now and... oh my goodness, what is all of this?",
    "What happened to all of the people here? Why are they all dead?",
    "This guy's head is literally on a stick! Oh my god, that's way too scary.",
    "And there's a bunch of blood everywhere. Oh no no, and what's in this?",
    "Oh my goodness, why are there a bunch of dead humans stuck in here?",
    "No no no, is this village haunted or something? Or is there a murderer nearby?",
    "This is super duper ultra bad! Oh my gosh, I need to get out of here, I need to get out of here!",
    "And I think this is the way out. Yes, yes! Okay, let me go here and... oh my goodness, that village is way too haunted.",
    "I need to get... oh my goodness, it isn't over!",
    "Why are there more dead humans here? And it's a gate to a castle-looking thing, or is that a house?",
    "Does the person that's living here know that there's a bunch of dead humans out here?",
    "But maybe I can get help from the person inside that house and get out of this forest.",
    "So you know what? Let me go through here and... wait a minute, why can I not go in?",
    "Excuse me, excuse me, can you let me in?",
    "Oh wait a minute, there's a keyhole here. Maybe I have to find a key to open it.",
    "Well, I'll go explore and try to find the key, but I don't wanna go too far because who knows what might be around here.",
    "What could have happened to all of these villagers to make them like that?",
    "But wait, this is another broken house and there's another chest in here.",
    "Don't mind if I do and... whoa, there's a bunch of rot and flesh here, more bones, and a wooden sword.",
    "That's gonna come in handy, and a fiddlestick and vermar? What is that? I have no idea.",
    "But at least I have a sword that will help me defend against others.",
    "But I haven't found the key yet, so I might have to go in the other direction, explore it that way to see if there's a key.",
    "Oh my goodness, this gets more scary every time I look at it.",
    "So hello, is there a key in here? There's a furnace, nothing in there.",
    "Can I go inside here? No, I can't fit.",
    "Where is this key? That road is blocked off, that road is blocked off and... wait a minute, there's another chest here!",
    "Maybe it's inside here. Let's look and... yes! I have a key along with some more rotted flesh and some wheat.",
    "This is perfect and it can be placed on a carved pumpkin.",
    "And what is all of this stuff? What is all of this for?",
    "I don't know, maybe they'll come in handy later, but at least I have a key to go inside.",
    "And I really really hope that the person inside living that house could help me because this is not what I signed up for.",
    "I am just lost, I just wanna go home.",
    "So I really hope I can leave and... there we go, the key has been placed and now I can go through and... oh my goodness, I feel much better now.",
    "Wait a minute, what is that? Uh-uh, who is that?",
    "Don't make any noise... wait a minute, what the heck just happened?",
    "It just zoomed in on a little villager over there and it looks like he was cooking something.",
    "I just got a warning that said don't make any noise. What does that mean? What does that mean?",
    "I am so super duper scared and... oh my goodness, oh my goodness, which way do I go? Which way do I go?",
    "Oh, I take back everything I said. I feel super duper bad now.",
    "Oh my goodness, I have a really bad feeling about this and... oh no, was that the doorbell?",
    "Was that... oh no, oh no, whatever did the villager that was just there... oh no, I didn't mean to!",
    "Oh my goodness, we gotta run, run!",
    "Oh my goodness, what's happening? What's happening? Why am I getting told to run? Why am I getting told to run?",
    "No no no no, I didn't mean to press that doorbell!",
    "Oh my gosh, it says to run, it says to run! Why am I running? Where am I running off to?",
    "No no no no, I need to get out of here!",
    "My goodness, let me run and... what? Wait, what? Why am I trapped in here?",
    "What the heck? Are you feeling sick? No no no, this is bad, please please!",
    "The villager... oh no, oh no, what's happening? What is happening?",
    "Oh my goodness, oh my goodness, I feel super... oh no, oh no, oh no!",
    "What is that? What is that? Where am I? Am I locked inside of a cage?",
    "Wait, what the heck just happened? I just blacked out and now I'm inside here!",
    "Oh my goodness, no no, how do I get out? If you're... this is terrible!",
    "That evil villager... oh my goodness, oh my goodness, everything is scaring me right now!",
    "That villager literally just trapped me and he brought me inside here.",
    "No no, I'm just trying to get back home and of course I get caught by this weird evil villager.",
    "I thought he could have helped me but he must be the one that killed all of those other innocent villagers.",
    "And there's a bunch of doors here. Can I open them? No I can't, but there's a chest here too.",
    "And there's a diary inside along with some steak and a wooden axe.",
    "Let me read this diary and... what does it say?",
    "It looks like a diary made by a guy named Victor and he left us instructions on how to escape this place.",
    "And based on what I'm reading, I pretty much need to blow up a thing called a boiler room so I can escape through that.",
    "But to do that, I have to open six valves so I'll build up pressure in the boiler room so it explodes.",
    "So our mission right now is to open these six valves and the first valve I have to get to is a place called the torture chamber valve.",
    "Oh my gosh, that sounds super duper scary, but what does this lever do right here?",
    "Let's flick this and... oh, here we go!",
    "The torture chamber valve has been opened, which is good news but it's also bad news because I do not want to go into a thing called the torture chamber.",
    "And oh my goodness, what is all of this stuff? Can I squeeze through here and... yes I can!",
    "Alright, but where do I go from here? And there's a security camera over there.",
    "Is he watching me? Hello, hello, can you watch me? Are you seeing me?",
    "Oh my goodness, I am so nervous. What is the evil villager gonna do to us?",
    "Like, what is around all of this? It just looks like a place where he does experiments or something.",
    "But wait a minute, a dungeon? Why does he have a dungeon in his house?",
    "And oh my goodness, is that a person? He keeps people in his dungeon!",
    "And oh my goodness, here is another guy that must have been trapped.",
    "Hello buddy, buddy are you okay? You gotta speak to me man, you gotta speak to me!",
    "Oh, 'run', that's all you can tell me?",
    "Oh no, I am so super nervous, very nervous now. This is bad, this is bad.",
    "And oh my goodness, this guy is huge! How did they ever capture him?",
    "And oh my goodness, look at his eyes and his teeth! Why does he look so scary?",
    "Oh my goodness, how did they do this to you? You're saying 'run' too?",
    "Why is everybody telling me to run? Well, probably because the evil villager is gonna like, kill me somehow.",
    "But still, this is so scary and he has even more people here. Look how terrified they look!",
    "Is there any way I can escape through this place? No, there's nothing here, nothing in this dungeon cell either.",
    "There's nothing in here too. Well, what could there be to help me escape?",
    "And I'm so sorry guys, but I don't think I can escape with you. You guys are way too noisy and there's just too many people.",
    "So I have to do this by myself and there's a thing called a security... what's inside the security room?",
    "Oh wait, there's a bunch of cameras here. Wait, can I actually watch the cameras? Let me see and... wait, what? What just happened?",
    "Hello? Literally nothing just happened, the camera just disappeared.",
    "Well, I'll just figure that out later. Maybe the cameras just aren't in function or something.",
    "But let's keep exploring and... oh, oh this is the torture chamber. Okay, I see, I see.",
    "So we need to figure out how to open the valve over here first and is there anything else this way?",
    "And whoa, there's a set of stairs here. Alright, let me go down over here.",
    "Is there anything here? Nope, I don't see anything.",
    "Here's the living... what is that? Is that... is that the evil villager?",
    "No no way, no way, no way! Wait, wait, there's a chest here and there's a bunch of stuff in here including a shield.",
    "Okay, let me equip that real quickly and... oh no no no no!",
    "Oh my god, he's right there, he's right there, he's right there!",
    "No problem, so stop stop stop stop! Okay, can I get him? Can I kill him?"
]